version: "3.9"
services:
  mysql:
    image: mysql
    container_name: bd_mysql
    ports:
      - 24306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=raul
      - MYSQL_PASSWORD=raul
      - MYSQL_DATABASE=empresa
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8912:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1

